// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch_api_panic`, `encode_json`, `into_bytes`, `into_json`, `into_status`, `panic_message`, `parse_json`, `with_service`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessengerMlsBridge>>
abstract class MessengerMlsBridge implements RustOpaqueInterface {
  ApiStatus clearPendingCommit({required String inputJson});

  static MessengerMlsBridge create() =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeCreate();

  ApiStatus createClient({required String inputJson});

  ApiJsonResponse createGroup({required String inputJson});

  ApiJsonResponse createKeyPackages({required int count});

  ApiStatus dropGroup({required String inputJson});

  ApiJsonResponse encryptMessage({required String inputJson});

  ApiBytesResponse exportClientState();

  ApiJsonResponse getClientId();

  ApiJsonResponse getGroupState({required String inputJson});

  ApiJsonResponse handleIncoming({required String inputJson});

  ApiJsonResponse hasPendingCommit({required String inputJson});

  ApiJsonResponse invite({required String inputJson});

  ApiJsonResponse joinFromWelcome({required List<int> welcomeMessage});

  ApiJsonResponse listGroups();

  ApiJsonResponse listMembers({required String inputJson});

  ApiStatus markKeyPackagesUploaded({required String inputJson});

  ApiJsonResponse mergePendingCommit({required String inputJson});

  ApiJsonResponse remove({required String inputJson});

  ApiStatus restoreClient({required List<int> data});

  ApiJsonResponse selfUpdate({required String inputJson});
}

class ApiBytesResponse {
  final int code;
  final String message;
  final Uint8List data;

  const ApiBytesResponse({
    required this.code,
    required this.message,
    required this.data,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBytesResponse &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          data == other.data;
}

class ApiJsonResponse {
  final int code;
  final String message;
  final String json;

  const ApiJsonResponse({
    required this.code,
    required this.message,
    required this.json,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ json.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiJsonResponse &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          json == other.json;
}

class ApiStatus {
  final int code;
  final String message;

  const ApiStatus({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiStatus &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}
