// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class ChatCoreBridge
    extends
        BaseEntrypoint<
          ChatCoreBridgeApi,
          ChatCoreBridgeApiImpl,
          ChatCoreBridgeWire
        > {
  @internal
  static final instance = ChatCoreBridge._();

  ChatCoreBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    ChatCoreBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required ChatCoreBridgeApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<ChatCoreBridgeApiImpl, ChatCoreBridgeWire>
  get apiImplConstructor => ChatCoreBridgeApiImpl.new;

  @override
  WireConstructor<ChatCoreBridgeWire> get wireConstructor =>
      ChatCoreBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1009862852;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'chat_core',
        ioDirectory: '../../target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class ChatCoreBridgeApi extends BaseApi {
  ApiStatus crateFrbApiMessengerMlsBridgeClearPendingCommit({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  MessengerMlsBridge crateFrbApiMessengerMlsBridgeCreate();

  ApiStatus crateFrbApiMessengerMlsBridgeCreateClient({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeCreateGroup({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeCreateKeyPackages({
    required MessengerMlsBridge that,
    required int count,
  });

  ApiStatus crateFrbApiMessengerMlsBridgeDropGroup({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeEncryptMessage({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiBytesResponse crateFrbApiMessengerMlsBridgeExportClientState({
    required MessengerMlsBridge that,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeGetClientId({
    required MessengerMlsBridge that,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeGetGroupState({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeHandleIncoming({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeHasPendingCommit({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeInvite({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeJoinFromWelcome({
    required MessengerMlsBridge that,
    required List<int> welcomeMessage,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeListGroups({
    required MessengerMlsBridge that,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeListMembers({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiStatus crateFrbApiMessengerMlsBridgeMarkKeyPackagesUploaded({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeMergePendingCommit({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeRemove({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  ApiStatus crateFrbApiMessengerMlsBridgeRestoreClient({
    required MessengerMlsBridge that,
    required List<int> data,
  });

  ApiJsonResponse crateFrbApiMessengerMlsBridgeSelfUpdate({
    required MessengerMlsBridge that,
    required String inputJson,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MessengerMlsBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MessengerMlsBridge;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MessengerMlsBridgePtr;
}

class ChatCoreBridgeApiImpl extends ChatCoreBridgeApiImplPlatform
    implements ChatCoreBridgeApi {
  ChatCoreBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ApiStatus crateFrbApiMessengerMlsBridgeClearPendingCommit({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeClearPendingCommitConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeClearPendingCommitConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_clear_pending_commit",
        argNames: ["that", "inputJson"],
      );

  @override
  MessengerMlsBridge crateFrbApiMessengerMlsBridgeCreate() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeCreateConstMeta =>
      const TaskConstMeta(debugName: "MessengerMlsBridge_create", argNames: []);

  @override
  ApiStatus crateFrbApiMessengerMlsBridgeCreateClient({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeCreateClientConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeCreateClientConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_create_client",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeCreateGroup({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeCreateGroupConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeCreateGroupConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_create_group",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeCreateKeyPackages({
    required MessengerMlsBridge that,
    required int count,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_u_32(count, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeCreateKeyPackagesConstMeta,
        argValues: [that, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeCreateKeyPackagesConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_create_key_packages",
        argNames: ["that", "count"],
      );

  @override
  ApiStatus crateFrbApiMessengerMlsBridgeDropGroup({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeDropGroupConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeDropGroupConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_drop_group",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeEncryptMessage({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeEncryptMessageConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeEncryptMessageConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_encrypt_message",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiBytesResponse crateFrbApiMessengerMlsBridgeExportClientState({
    required MessengerMlsBridge that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_bytes_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeExportClientStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeExportClientStateConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_export_client_state",
        argNames: ["that"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeGetClientId({
    required MessengerMlsBridge that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeGetClientIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeGetClientIdConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_get_client_id",
        argNames: ["that"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeGetGroupState({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeGetGroupStateConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeGetGroupStateConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_get_group_state",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeHandleIncoming({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeHandleIncomingConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeHandleIncomingConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_handle_incoming",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeHasPendingCommit({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeHasPendingCommitConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeHasPendingCommitConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_has_pending_commit",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeInvite({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeInviteConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeInviteConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_invite",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeJoinFromWelcome({
    required MessengerMlsBridge that,
    required List<int> welcomeMessage,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(welcomeMessage, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeJoinFromWelcomeConstMeta,
        argValues: [that, welcomeMessage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeJoinFromWelcomeConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_join_from_welcome",
        argNames: ["that", "welcomeMessage"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeListGroups({
    required MessengerMlsBridge that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeListGroupsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeListGroupsConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_list_groups",
        argNames: ["that"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeListMembers({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeListMembersConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeListMembersConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_list_members",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiStatus crateFrbApiMessengerMlsBridgeMarkKeyPackagesUploaded({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_status,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateFrbApiMessengerMlsBridgeMarkKeyPackagesUploadedConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateFrbApiMessengerMlsBridgeMarkKeyPackagesUploadedConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_mark_key_packages_uploaded",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeMergePendingCommit({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeMergePendingCommitConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeMergePendingCommitConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_merge_pending_commit",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeRemove({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeRemoveConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeRemoveConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_remove",
        argNames: ["that", "inputJson"],
      );

  @override
  ApiStatus crateFrbApiMessengerMlsBridgeRestoreClient({
    required MessengerMlsBridge that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeRestoreClientConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeRestoreClientConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_restore_client",
        argNames: ["that", "data"],
      );

  @override
  ApiJsonResponse crateFrbApiMessengerMlsBridgeSelfUpdate({
    required MessengerMlsBridge that,
    required String inputJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
            that,
            serializer,
          );
          sse_encode_String(inputJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_json_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiMessengerMlsBridgeSelfUpdateConstMeta,
        argValues: [that, inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMessengerMlsBridgeSelfUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerMlsBridge_self_update",
        argNames: ["that", "inputJson"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MessengerMlsBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MessengerMlsBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge;

  @protected
  MessengerMlsBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessengerMlsBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MessengerMlsBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessengerMlsBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MessengerMlsBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessengerMlsBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiBytesResponse dco_decode_api_bytes_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiBytesResponse(
      code: dco_decode_u_32(arr[0]),
      message: dco_decode_String(arr[1]),
      data: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  ApiJsonResponse dco_decode_api_json_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiJsonResponse(
      code: dco_decode_u_32(arr[0]),
      message: dco_decode_String(arr[1]),
      json: dco_decode_String(arr[2]),
    );
  }

  @protected
  ApiStatus dco_decode_api_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiStatus(
      code: dco_decode_u_32(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  MessengerMlsBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessengerMlsBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MessengerMlsBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessengerMlsBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MessengerMlsBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessengerMlsBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiBytesResponse sse_decode_api_bytes_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_u_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return ApiBytesResponse(
      code: var_code,
      message: var_message,
      data: var_data,
    );
  }

  @protected
  ApiJsonResponse sse_decode_api_json_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_u_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_json = sse_decode_String(deserializer);
    return ApiJsonResponse(
      code: var_code,
      message: var_message,
      json: var_json,
    );
  }

  @protected
  ApiStatus sse_decode_api_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_u_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ApiStatus(code: var_code, message: var_message);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    MessengerMlsBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessengerMlsBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    MessengerMlsBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessengerMlsBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerMlsBridge(
    MessengerMlsBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessengerMlsBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_bytes_response(
    ApiBytesResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_api_json_response(
    ApiJsonResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.json, serializer);
  }

  @protected
  void sse_encode_api_status(ApiStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class MessengerMlsBridgeImpl extends RustOpaque implements MessengerMlsBridge {
  // Not to be used by end users
  MessengerMlsBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MessengerMlsBridgeImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: ChatCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_MessengerMlsBridge,
    rustArcDecrementStrongCount: ChatCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_MessengerMlsBridge,
    rustArcDecrementStrongCountPtr: ChatCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_MessengerMlsBridgePtr,
  );

  ApiStatus clearPendingCommit({required String inputJson}) => ChatCoreBridge
      .instance
      .api
      .crateFrbApiMessengerMlsBridgeClearPendingCommit(
        that: this,
        inputJson: inputJson,
      );

  ApiStatus createClient({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeCreateClient(
        that: this,
        inputJson: inputJson,
      );

  ApiJsonResponse createGroup({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeCreateGroup(
        that: this,
        inputJson: inputJson,
      );

  ApiJsonResponse createKeyPackages({required int count}) => ChatCoreBridge
      .instance
      .api
      .crateFrbApiMessengerMlsBridgeCreateKeyPackages(that: this, count: count);

  ApiStatus dropGroup({required String inputJson}) => ChatCoreBridge
      .instance
      .api
      .crateFrbApiMessengerMlsBridgeDropGroup(that: this, inputJson: inputJson);

  ApiJsonResponse encryptMessage({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeEncryptMessage(
        that: this,
        inputJson: inputJson,
      );

  ApiBytesResponse exportClientState() => ChatCoreBridge.instance.api
      .crateFrbApiMessengerMlsBridgeExportClientState(that: this);

  ApiJsonResponse getClientId() => ChatCoreBridge.instance.api
      .crateFrbApiMessengerMlsBridgeGetClientId(that: this);

  ApiJsonResponse getGroupState({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeGetGroupState(
        that: this,
        inputJson: inputJson,
      );

  ApiJsonResponse handleIncoming({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeHandleIncoming(
        that: this,
        inputJson: inputJson,
      );

  ApiJsonResponse hasPendingCommit({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeHasPendingCommit(
        that: this,
        inputJson: inputJson,
      );

  ApiJsonResponse invite({required String inputJson}) => ChatCoreBridge
      .instance
      .api
      .crateFrbApiMessengerMlsBridgeInvite(that: this, inputJson: inputJson);

  ApiJsonResponse joinFromWelcome({required List<int> welcomeMessage}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeJoinFromWelcome(
        that: this,
        welcomeMessage: welcomeMessage,
      );

  ApiJsonResponse listGroups() => ChatCoreBridge.instance.api
      .crateFrbApiMessengerMlsBridgeListGroups(that: this);

  ApiJsonResponse listMembers({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeListMembers(
        that: this,
        inputJson: inputJson,
      );

  ApiStatus markKeyPackagesUploaded({required String inputJson}) =>
      ChatCoreBridge.instance.api
          .crateFrbApiMessengerMlsBridgeMarkKeyPackagesUploaded(
            that: this,
            inputJson: inputJson,
          );

  ApiJsonResponse mergePendingCommit({required String inputJson}) =>
      ChatCoreBridge.instance.api
          .crateFrbApiMessengerMlsBridgeMergePendingCommit(
            that: this,
            inputJson: inputJson,
          );

  ApiJsonResponse remove({required String inputJson}) => ChatCoreBridge
      .instance
      .api
      .crateFrbApiMessengerMlsBridgeRemove(that: this, inputJson: inputJson);

  ApiStatus restoreClient({required List<int> data}) => ChatCoreBridge
      .instance
      .api
      .crateFrbApiMessengerMlsBridgeRestoreClient(that: this, data: data);

  ApiJsonResponse selfUpdate({required String inputJson}) =>
      ChatCoreBridge.instance.api.crateFrbApiMessengerMlsBridgeSelfUpdate(
        that: this,
        inputJson: inputJson,
      );
}
